"""Daily Priorities — suggests morning priorities based on calendar + tasks + milestones.

Surfaces 3-5 suggested key tasks each morning (generated by Claude from the
vault's hard dates, tasks, and project milestones) and persists David's curated
list to one file per day under ``99_System/Daily_Todos/YYYY-MM-DD.md``. Status
toggles and manual additions are written straight back to that file.

All vault writes go through :func:`core.vault.write_md`, which saves a ``.bak``
copy first (per the project's OneDrive-safe write policy).
"""
from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path

from core import markdown, vault
from core.config import SYSTEM_PATH, get_logger
from modules.agents.claude_cli import run_claude

logger = get_logger(__name__)

DAILY_DIR = SYSTEM_PATH / "Daily_Todos"

_README = """# Daily Todos

One file per day. Generated each morning when the dashboard is first opened.
Pattern: YYYY-MM-DD.md

Structure:
- ## Priorities — suggested by Claude based on hard dates + project milestones
- ## Added manually — David's additions throughout the day

Status toggles persist (- [ ] -> - [x]) directly via dashboard click.

Archive: files accumulate. Useful for retrospective pattern recognition over time.
"""


def daily_file_path(d: date | None = None) -> Path:
    d = d or date.today()
    return DAILY_DIR / f"{d.isoformat()}.md"


def daily_exists(d: date | None = None) -> bool:
    return daily_file_path(d).exists()


def _ensure_dir() -> None:
    """Create the Daily_Todos folder + its README on first use."""
    DAILY_DIR.mkdir(parents=True, exist_ok=True)
    readme = DAILY_DIR / "README.md"
    if not readme.exists():
        readme.write_text(_README, encoding="utf-8")


def suggest_priorities() -> dict:
    """Generate 3-5 priority suggestions for today based on vault context."""
    today = date.today()

    # Assemble context.
    tasks_md = vault.read_md(SYSTEM_PATH / "Task_Command_Center.md")
    projects_md = vault.read_md(SYSTEM_PATH / "Project_Index.md")

    # Get hard dates from the tasks file and keep the ones landing inside 14 days.
    hard_dates = markdown.parse_hard_dates(tasks_md)
    upcoming = [
        d for d in hard_dates
        if d.get("date") and 0 <= (d["date"] - today).days <= 14
    ]
    upcoming_str = "\n".join(
        f"- {d['date'].isoformat()} ({(d['date'] - today).days}d): {d['label']}"
        for d in upcoming
    )

    prompt = f"""You are David's personal chief of staff. Today is {today.strftime('%A, %B %d, %Y')}.

Suggest 3-5 PRIORITY tasks for David to tackle today, based on the context below.

Selection criteria:
- Hard deadlines approaching (within 7 days = high priority)
- Project milestones with near-term dates
- Critical project next steps
- Time-sensitive admin (payments, decisions, communications)
- Avoid suggesting things he can't realistically do today (e.g. don't suggest "vacation" or "wait for X")
- Prefer SPECIFIC, ACTIONABLE items over generic ones

Upcoming hard dates in next 14 days:
{upcoming_str if upcoming_str else "(none)"}

Tasks file:
{tasks_md[:3000]}

Projects file:
{projects_md[:2000]}

Output as JSON only:
{{
  "priorities": [
    {{
      "task": "Short clear task name",
      "rationale": "1-2 sentence why this is priority today",
      "deadline": "YYYY-MM-DD or null",
      "estimated_minutes": 30
    }}
  ],
  "summary": "1-sentence overview of the day's focus"
}}

Tone: direct, prioritized, no fluff. Recommend exactly 3-5 items.
"""
    try:
        result = run_claude(prompt, timeout=120)
    except Exception as exc:  # noqa: BLE001 - never hard-fail the morning panel
        logger.warning("suggest_priorities: run_claude failed: %s", exc)
        return {"priorities": [], "summary": "Could not generate suggestions."}

    match = re.search(r"\{.*\}", result, re.DOTALL)
    if not match:
        return {"priorities": [], "summary": "Could not generate suggestions."}
    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        logger.warning("suggest_priorities: malformed JSON from model")
        return {"priorities": [], "summary": "Could not generate suggestions."}


def create_daily_file(
    d: date | None = None,
    priorities: list | None = None,
    manual_items: list | None = None,
) -> Path:
    """Create the YYYY-MM-DD.md file with curated priorities."""
    _ensure_dir()
    d = d or date.today()
    path = daily_file_path(d)

    lines = [f"# Today — {d.isoformat()}", ""]
    lines.append(f"Generated {date.today().isoformat()}.")
    lines.append("")
    lines.append("## Priorities")
    lines.append("")

    for p in (priorities or []):
        lines.append(f"- [ ] {p['task']}")
        if p.get("rationale"):
            lines.append(f"  - _why:_ {p['rationale']}")

    if manual_items:
        lines.append("")
        lines.append("## Added manually")
        lines.append("")
        for item in manual_items:
            lines.append(f"- [ ] {item}")

    vault.write_md(path, "\n".join(lines))
    return path


def add_to_daily(text: str, d: date | None = None) -> None:
    """Append a manual item to today's file."""
    d = d or date.today()
    path = daily_file_path(d)
    if not path.exists():
        create_daily_file(d, [], [text])
        return
    content = path.read_text(encoding="utf-8")
    if "## Added manually" not in content:
        content += "\n\n## Added manually\n"
    content += f"\n- [ ] {text}"
    vault.write_md(path, content)


def toggle_daily_item(line_text: str, d: date | None = None) -> None:
    """Toggle a [ ] / [x] item by matching text."""
    d = d or date.today()
    path = daily_file_path(d)
    if not path.exists():
        return
    content = path.read_text(encoding="utf-8")
    lines = content.splitlines()
    for i, line in enumerate(lines):
        if line_text.lower() in line.lower() and ("- [ ]" in line or "- [x]" in line):
            if "- [ ]" in line:
                lines[i] = line.replace("- [ ]", "- [x]", 1)
            else:
                lines[i] = line.replace("- [x]", "- [ ]", 1)
            break
    vault.write_md(path, "\n".join(lines))


def read_today() -> dict:
    """Read today's file, parse into structured data."""
    path = daily_file_path()
    if not path.exists():
        return {"exists": False, "priorities": [], "manual": []}
    content = path.read_text(encoding="utf-8")
    priorities: list[dict] = []
    manual: list[dict] = []
    section: str | None = None
    for line in content.splitlines():
        if line.startswith("## Priorities"):
            section = "priorities"
            continue
        if line.startswith("## Added manually"):
            section = "manual"
            continue
        m = re.match(r"^\s*-\s*\[([ x])\]\s*(.+)$", line)
        if m:
            item = {"text": m.group(2), "checked": m.group(1) == "x"}
            if section == "priorities":
                priorities.append(item)
            elif section == "manual":
                manual.append(item)
    return {"exists": True, "priorities": priorities, "manual": manual}
